# Generated by Django 4.2.2 on 2023-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
    ]
