# Generated by Django 4.2.2 on 2023-09-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_notifications_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notifications',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='notification_receiver', to='account.profile'),
        ),
    ]
