# Generated by Django 4.2.2 on 2023-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_notifications_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
