# Generated by Django 4.2.2 on 2023-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
    ]
