# Generated by Django 4.2.2 on 2023-09-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_room_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='created',
        ),
    ]
