# Generated by Django 4.2.2 on 2023-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_message_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_images/user-default.jpg', null=True, upload_to='images/profile_images/'),
        ),
    ]
