# Generated by Django 4.2.2 on 2023-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/user-default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
